apiVersion: v1
kind: Service
metadata:
  name: event-backend-service
  namespace: event-app
  labels:
    app: event-backend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "event-backend-lb"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: event-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
